### ISSUE TITLE
Self host Models weights using Torrent

### ISSUE THREAD

**Issue by filopedraz** [filopedraz/from-hf-to-torrent#1]
### Description

We need to self-host the weights using Torrent on a Hetzener machine. The steps are the following:

1. Run the `transmission` daemon using `docker-compose`
2. Download the weights from HF
3. Create a `.torrent` file for each folder containing the weights.
4. Seed the torrents using the folder used for dumping the weights.

We want to seed the following models:

- [ ] premai-io/CodeLlama-34b-Instruct-hf
- [ ] petals-team/StableBeluga2
- [ ] tiiuae/falcon-180B-chat

### Missing 

Most of the logic and the scripts are in the repo. The entire flow must be tested and fixed accordingly.

**Comment by casperdcl** [comment]
surely we should have WebSeeds[^torf-webseed][^bep19] too?

[^bep19]: http://bittorrent.org/beps/bep_0019.html
[^torf-webseed]: https://torf.readthedocs.io/en/stable/#torf.Torrent.webseeds

In pseudocode:

```sh
wget https://example.com/model.hf
torrent create -o model.torrent model.hf
torrent modify --add-url https://example.com/model.hf model.torrent  # proposed
torrent serve model.torrent
```

**Comment by filopedraz** [comment]
Sure, good for me. Let me know when you need access to the machine :)

**Comment by biswaroop1547** [comment]
hi need access :")

**Comment by biswaroop1547** [comment]
For having a separate webseed url, we should be using a new instance which will just serve the files over http. Are we okay with using another machine for this? or expose files over http on the same machine?

we cannot directly serve the files from hf link (using git lfs) e.g -`https://huggingface.co/premai-io/CodeLlama-34b-Instruct-hf` as a webseed url. And if using the same server for seeding torrent + hosting webseed url, it'll cause much higher load on the machine.

Ideally for webseed url we should have a mirror link (e.g `https://mirror.premai.io/models/`) which will point to a new instance hosting models.


I think we can start with serving webseed url from the same machine and later move if required.

**Comment by biswaroop1547** [comment]
I think we can start with serving webseed url from the same machine and later move if required.
